import '@/styles/globals.css'
import styled from 'styled-components';
import Head from 'next/head'

export const Wrapper = styled.div`
  max-width: 1600px;
  margin: 0 auto;
  position: relative;
  min-height: 100vh;
`;

export const Container = styled.div`
  padding: 0px 0px;
`;

function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
      <title>Fraime</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Wrapper>
      <Container>
        <Component {...pageProps} />
      </Container>
    </Wrapper>
    </>
  )
}

export default MyApp